### ISSUE TITLE
fserver没有理会wasp.zookeeper.quorum的配置

### ISSUE THREAD

**Issue by JoeAu** [alibaba/wasp#1]
fserver所在的机器并没有zk，所以一直在尝试localhost:2181 

<pre>
<code>
2013-07-25 17:45:02,119 INFO org.apache.zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=180000 watcher=hconnection
2013-07-25 17:45:02,143 INFO org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper: The identifier of this process is 18477@data1
2013-07-25 17:45:02,149 INFO org.apache.zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (Unable to locate a login configuration)
2013-07-25 17:45:02,157 WARN org.apache.zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:599)
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
2013-07-25 17:45:02,269 INFO org.apache.zookeeper.ClientCnxn: Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (Unable to locate a login configuration)
2013-07-25 17:45:02,270 WARN org.apache.zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:599)
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
2013-07-25 17:45:02,276 WARN org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper exception: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master
2013-07-25 17:45:02,277 INFO org.apache.hadoop.hbase.util.RetryCounter: Sleeping 2000ms before retry #1...
2013-07-25 17:45:03,375 INFO org.apache.zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (Unable to locate a login configuration)
2013-07-25 17:45:03,375 WARN org.apache.zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:599)
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
2013-07-25 17:45:03,477 INFO org.apache.zookeeper.ClientCnxn: Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (Unable to locate a login configuration)
2013-07-25 17:45:03,477 WARN org.apache.zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:599)
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)

</code>
</pre>

**Comment by jaywong85** [comment]
请检查下wasp-site.xml的配置。zk是通过wasp.zookeeper.quorum来配置

**Comment by fishCi** [comment]
请问wasp-site.xml改如何配置，和hbase-site.xml一样么？弱弱的问，我该肿么运行呢~我试着mvn package，然后有个TestAtomicOperation.java的单元测试一直卡着，然后就超时build failed....不知道问的问题是不是太小白了...原谅我很菜吧，刚解除hbase不久...

**Comment by haosdent** [comment]
@caixin0219 你可以看下中文版的wiki，试着安装下有木有问题。地址 https://github.com/alibaba/wasp/wiki/Chinese

**Comment by JoeAu** [comment]
@jaywong85 配置有wasp.zookeeper.quorum的

**Comment by jaywong85** [comment]
@caixin0219 mvn clean package -Dmaven.test.skip=true。然后把target包下面的wasp.jar 拷贝到工程根目录

**Comment by jaywong85** [comment]
配置其实读到了。zk方面的host设定maybe有些问题

**Comment by jaywong85** [comment]
我最近一台机器上也出现这种问题。原因是我没有配置hbase-site.xml，@JoeAu 配置下看看
