### ISSUE TITLE
入库的同时，查询报错，无法获取返回的数据

### ISSUE THREAD

**Issue by ihadoop** [alibaba/wasp#16]
13/08/12 15:17:59 INFO jdbc.JdbcConnection: Connection conn = DriverManager.getConnection("jdbc:wasp:", "", "");
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.5-1392090, built on 09/30/2012 17:52 GMT
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:host.name=cstor
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:java.version=1.7.0_02
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:java.home=C:\Program Files\Java\jre7
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:java.class.path=C:\Users\cstor\workspace\wasp-test\bin;C:\Users\cstor\workspace\wasp-test\lib\activation-1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\aopalliance-1.0.jar;C:\Users\cstor\workspace\wasp-test\lib\asm-3.1.jar;C:\Users\cstor\workspace\wasp-test\lib\avro-1.5.3.jar;C:\Users\cstor\workspace\wasp-test\lib\avro-ipc-1.5.3.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-beanutils-1.7.0.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-beanutils-core-1.8.0.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-cli-1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-codec-1.7.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-collections-3.2.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-configuration-1.6.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-digester-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-el-1.0.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-httpclient-3.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-io-2.4.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-lang-2.6.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-logging-1.1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-math-2.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-net-1.4.1.jar;C:\Users\cstor\workspace\wasp-test\lib\core-3.1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\druid-0.2.9.jar;C:\Users\cstor\workspace\wasp-test\lib\ftplet-api-1.0.0.jar;C:\Users\cstor\workspace\wasp-test\lib\ftpserver-core-1.0.0.jar;C:\Users\cstor\workspace\wasp-test\lib\ftpserver-deprecated-1.0.0-M2.jar;C:\Users\cstor\workspace\wasp-test\lib\guava-12.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\hadoop-core-1.0.3.jar;C:\Users\cstor\workspace\wasp-test\lib\hadoop-test-1.0.3.jar;C:\Users\cstor\workspace\wasp-test\lib\hamcrest-core-1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\hbase-0.94.1-tests.jar;C:\Users\cstor\workspace\wasp-test\lib\hbase-0.94.1.jar;C:\Users\cstor\workspace\wasp-test\lib\high-scale-lib-1.1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\hsqldb-1.8.0.10.jar;C:\Users\cstor\workspace\wasp-test\lib\htrace-1.49.jar;C:\Users\cstor\workspace\wasp-test\lib\httpclient-4.1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\httpcore-4.1.3.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-core-asl-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-jaxrs-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-mapper-asl-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-xc-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jamon-runtime-2.3.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jasper-compiler-5.5.23.jar;C:\Users\cstor\workspace\wasp-test\lib\jasper-runtime-5.5.23.jar;C:\Users\cstor\workspace\wasp-test\lib\jaxb-api-2.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jaxb-impl-2.2.3-1.jar;C:\Users\cstor\workspace\wasp-test\lib\jersey-core-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jersey-json-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jersey-server-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jets3t-0.7.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jettison-1.3.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jetty-6.1.26.jar;C:\Users\cstor\workspace\wasp-test\lib\jetty-util-6.1.26.jar;C:\Users\cstor\workspace\wasp-test\lib\jruby-complete-1.6.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jsp-2.1-6.1.14.jar;C:\Users\cstor\workspace\wasp-test\lib\jsp-api-2.1-6.1.14.jar;C:\Users\cstor\workspace\wasp-test\lib\jsr305-1.3.9.jar;C:\Users\cstor\workspace\wasp-test\lib\junit-4.10.jar;C:\Users\cstor\workspace\wasp-test\lib\kfs-0.3.jar;C:\Users\cstor\workspace\wasp-test\lib\libthrift-0.8.0.jar;C:\Users\cstor\workspace\wasp-test\lib\log4j-1.2.17.jar;C:\Users\cstor\workspace\wasp-test\lib\metrics-core-2.1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\mina-core-2.0.0-M5.jar;C:\Users\cstor\workspace\wasp-test\lib\mockito-all-1.9.0.jar;C:\Users\cstor\workspace\wasp-test\lib\netty-3.2.4.Final.jar;C:\Users\cstor\workspace\wasp-test\lib\netty-3.5.0.Final.jar;C:\Users\cstor\workspace\wasp-test\lib\oro-2.0.8.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-java-2.4.1.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-java-format-1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-rpc-pro-demo-2.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-rpc-pro-duplex-2.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-streamer-pro-1.2.3.jar;C:\Users\cstor\workspace\wasp-test\lib\servlet-api-2.5-6.1.14.jar;C:\Users\cstor\workspace\wasp-test\lib\slf4j-api-1.4.3.jar;C:\Users\cstor\workspace\wasp-test\lib\slf4j-log4j12-1.4.3.jar;C:\Users\cstor\workspace\wasp-test\lib\snappy-java-1.0.3.2.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-aop-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-asm-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-beans-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-context-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-core-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-expression-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\stax-api-1.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\velocity-1.7.jar;C:\Users\cstor\workspace\wasp-test\lib\wasp-0.10.jar;C:\Users\cstor\workspace\wasp-test\lib\xmlenc-0.52.jar;C:\Users\cstor\workspace\wasp-test\lib\zookeeper-3.4.5.jar
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:java.library.path=C:\Program Files\Java\jre7\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\MinGW\bin;C:\Program Files (x86)\Git\bin;C:\tools\apache-maven-3.0.5\bin;C:\Program Files (x86)\Common Files\NetSarang;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Common Files\Ulead Systems\MPEG;C:\Program Files\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;C:\Program Files (x86)\Intel\Services\IPT\;C:\Program Files (x86)\Common Files\Lenovo;C:\Program Files\TortoiseSVN\bin;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Program Files (x86)\VisualSVN\bin;C:\Program Files (x86)\QuickTime\QTSystem\;.
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=C:\Users\cstor\AppData\Local\Temp\
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:os.name=Windows 7
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:os.version=6.1
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:user.name=cstor
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:user.home=C:\Users\cstor
13/08/12 15:17:59 INFO zookeeper.ZooKeeper: Client environment:user.dir=C:\Users\cstor\workspace\wasp-test
13/08/12 15:18:00 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=192.168.6.154:2181,192.168.6.152:2181,192.168.6.156:2181,192.168.6.155:2181 sessionTimeout=180000 watcher=fclient:
13/08/12 15:18:00 INFO zookeeper.RecoverableZooKeeper: The identifier of this process is 7276@cstor
13/08/12 15:18:00 INFO zookeeper.ClientCnxn: Opening socket connection to server hx3/192.168.6.154:2181. Will not attempt to authenticate using SASL (unknown error)
13/08/12 15:18:00 INFO zookeeper.ClientCnxn: Socket connection established to hx3/192.168.6.154:2181, initiating session
13/08/12 15:18:00 INFO zookeeper.ClientCnxn: Session establishment complete on server hx3/192.168.6.154:2181, sessionid = 0x2407115b72e0022, negotiated timeout = 180000
1111
13/08/12 15:18:00 INFO ipc.NettyTransceiver: Successfully connected to bookie: hx2/192.168.6.156:50501
13/08/12 15:18:00 INFO client.FClientCallable: withRetries attempt 0 of 10 failed; retrying after sleep of 1000
13/08/12 15:18:01 INFO ipc.NettyTransceiver: Successfully connected to bookie: hx8/192.168.6.158:50501
13/08/12 15:18:02 INFO client.FClientCallable: withRetries attempt 1 of 10 failed; retrying after sleep of 1000
13/08/12 15:18:03 INFO client.FClientCallable: withRetries attempt 2 of 10 failed; retrying after sleep of 1000
13/08/12 15:18:04 INFO ipc.NettyTransceiver: Successfully connected to bookie: hx3/192.168.6.154:50501
13/08/12 15:18:04 INFO client.FClientCallable: withRetries attempt 3 of 10 failed; retrying after sleep of 2000
13/08/12 15:18:06 INFO client.FClientCallable: withRetries attempt 4 of 10 failed; retrying after sleep of 2000
13/08/12 15:18:08 INFO ipc.NettyTransceiver: Successfully connected to bookie: hx5/192.168.6.155:50501
13/08/12 15:18:08 INFO client.FClientCallable: withRetries attempt 5 of 10 failed; retrying after sleep of 4000
13/08/12 15:18:12 INFO client.FClientCallable: withRetries attempt 6 of 10 failed; retrying after sleep of 4000
13/08/12 15:18:16 INFO client.FClientCallable: withRetries attempt 7 of 10 failed; retrying after sleep of 8000
13/08/12 15:18:24 INFO client.FClientCallable: withRetries attempt 8 of 10 failed; retrying after sleep of 16000
13/08/12 15:18:40 INFO client.FClientCallable: withRetries attempt 9 of 10 failed; retrying after sleep of 32000
13/08/12 15:19:12 ERROR result.ResultRemote: FClinet execute sql error
com.alibaba.wasp.client.RetriesExhaustedException: Failed after attempts=10, exceptions:
Mon Aug 12 15:18:00 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:02 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:03 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:04 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:06 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:08 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:12 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:16 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:24 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:40 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException

```
at com.alibaba.wasp.client.ServerCallable.withRetries(ServerCallable.java:181)
at com.alibaba.wasp.client.FClient.execute(FClient.java:104)
at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:228)
at com.alibaba.wasp.jdbc.result.ResultRemote.<init>(ResultRemote.java:89)
at com.alibaba.wasp.jdbc.command.CommandRemote.executeQuery(CommandRemote.java:119)
at com.alibaba.wasp.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:91)
at com.Select.main(Select.java:32)
```

Exception in thread "main" java.lang.RuntimeException: com.alibaba.wasp.client.RetriesExhaustedException: Failed after attempts=10, exceptions:
Mon Aug 12 15:18:00 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:02 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:03 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:04 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:06 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:08 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:12 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:16 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:24 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:40 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException

```
at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:243)
at com.alibaba.wasp.jdbc.result.ResultRemote.<init>(ResultRemote.java:89)
at com.alibaba.wasp.jdbc.command.CommandRemote.executeQuery(CommandRemote.java:119)
at com.alibaba.wasp.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:91)
at com.Select.main(Select.java:32)
```

Caused by: com.alibaba.wasp.client.RetriesExhaustedException: Failed after attempts=10, exceptions:
Mon Aug 12 15:18:00 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:02 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:03 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:04 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:06 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:08 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:12 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:16 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:24 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException
Mon Aug 12 15:18:40 CST 2013, com.alibaba.wasp.client.FClientCallable@437ef115, java.io.IOException: java.lang.NullPointerException

```
at com.alibaba.wasp.client.ServerCallable.withRetries(ServerCallable.java:181)
at com.alibaba.wasp.client.FClient.execute(FClient.java:104)
at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:228)
... 4 more
```

**Comment by jaywong85** [comment]
fserver的log发一下

**Comment by ihadoop** [comment]
2013-08-06 14:05:03,783 INFO com.alibaba.wasp.fserver.FServer: Closing user entityGroups
2013-08-06 14:05:03,810 ERROR com.alibaba.wasp.fserver.EntityGroup: Getting last uncommited transaction of redo log failed
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.j
ava:1961)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1996)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
        at com.alibaba.wasp.fserver.redo.RedoLog.lastUnCommitedTransaction(RedoLog.java:195)
        at com.alibaba.wasp.fserver.EntityGroup.run(EntityGroup.java:1162)
        at java.lang.Thread.run(Thread.java:662)
2013-08-06 14:05:03,810 ERROR com.alibaba.wasp.fserver.EntityGroup: Getting last uncommited transaction of redo log failed
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.j
ava:1961)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1996)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
        at com.alibaba.wasp.fserver.redo.RedoLog.lastUnCommitedTransaction(RedoLog.java:195)
        at com.alibaba.wasp.fserver.EntityGroup.run(EntityGroup.java:1162)
        at java.lang.Thread.run(Thread.java:662)
2013-08-06 14:05:03,810 ERROR com.alibaba.wasp.fserver.EntityGroup: Getting last uncommited transaction of redo log failed
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.j
ava:1961)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1996)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
        at com.alibaba.wasp.fserver.redo.RedoLog.lastUnCommitedTransaction(RedoLog.java:195)
2013-08-12

13574798

发件人：jaywong notifications@github.com
发送时间：2013-08-12 15:21
主题：Re: [wasp] 入库的同时，查询报错，无法获取返回的数据 (#16)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

fserver的log发一下

**Comment by ihadoop** [comment]
com.google.protobuf.ServiceException: com.alibaba.wasp.ipc.ServerNotRunningYetException: IPC server unable to read call parameters:Ser
ver is not running yet
        at com.alibaba.wasp.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:178)
        at $Proxy6.fServerStartup(Unknown Source)
        at com.alibaba.wasp.fserver.FServer.reportForDuty(FServer.java:781)
        at com.alibaba.wasp.fserver.FServer.run(FServer.java:534)
        at java.lang.Thread.run(Thread.java:662)
Caused by: com.alibaba.wasp.ipc.ServerNotRunningYetException: IPC server unable to read call parameters:Server is not running yet
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:95)
        at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:79)
        at com.alibaba.wasp.ipc.NettyTransceiver.processResponse(NettyTransceiver.java:544)
        at com.alibaba.wasp.ipc.NettyTransceiver.call(NettyTransceiver.java:496)
        at com.alibaba.wasp.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:162)
        ... 4 more
Caused by: org.apache.hadoop.ipc.RemoteException: IPC server unable to read call parameters:Server is not running yet
:100000  
: error:
java.io.IOException: java.lang.NullPointerException
        at com.alibaba.wasp.plan.BaseDriver.execute(BaseDriver.java:166)
        at com.alibaba.wasp.fserver.FServer.execute(FServer.java:1191)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.alibaba.wasp.ipc.ProtobufRpcEngine$Server.call(ProtobufRpcEngine.java:272)
        at com.alibaba.wasp.ipc.NettyServer$NettyServerWaspHandler.messageReceived(NettyServer.java:249)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
        at com.alibaba.wasp.ipc.NettyServer$NettyServerWaspHandler.handleUpstream(NettyServer.java:186)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:754)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:69)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.NullPointerException
        at com.alibaba.wasp.meta.RowBuilder.buildStartkeyAndEndkey(RowBuilder.java:81)
        at com.alibaba.wasp.plan.parser.druid.FMetaEventOperation.getStartkeyAndEndkey(FMetaEventOperation.java:313)
        at com.alibaba.wasp.plan.parser.druid.DruidDQLParser.convertToQueryPlan(DruidDQLParser.java:235)
        at com.alibaba.wasp.plan.parser.druid.DruidDQLParser.getSelectPlan(DruidDQLParser.java:160)
        at com.alibaba.wasp.plan.parser.druid.DruidDQLParser.generatePlan(DruidDQLParser.java:103)
        at com.alibaba.wasp.plan.parser.WaspParser.generatePlan(WaspParser.java:174)
        at com.alibaba.wasp.plan.BaseDriver.execute(BaseDriver.java:160)
        ... 14 more

2013-08-12

13574798

发件人：jaywong notifications@github.com
发送时间：2013-08-12 15:21
主题：Re: [wasp] 入库的同时，查询报错，无法获取返回的数据 (#16)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

fserver的log发一下

**Comment by jaywong85** [comment]
应该是EntityGroup被下线了。数据写不进去。你可以找一下日志。看看eg为什么被下线。

**Comment by ihadoop** [comment]
过一会竟然好了，呵呵

2013-08-12

13574798

发件人：jaywong notifications@github.com
发送时间：2013-08-12 15:47
主题：Re: [wasp] 入库的同时，查询报错，无法获取返回的数据 (#16)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

应该是EntityGroup被下线了。数据写不进去。你可以找一下日志。看看eg为什么被下线。

**Comment by jaywong85** [comment]
那应该是EG还没有上线完成。

**Comment by ihadoop** [comment]
单表随着数据库的增多，入库速度很明显就慢了

2013-08-12

13574798

发件人：jaywong notifications@github.com
发送时间：2013-08-12 16:05
主题：Re: [wasp] 入库的同时，查询报错，无法获取返回的数据 (#16)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

那应该是EG还没有上线完成。

**Comment by jaywong85** [comment]
数据增多是指多到什么量级。
明显变慢RT是由多少降低为多少？

**Comment by ihadoop** [comment]
我们现在5台RS，32G，8核，一天入库4kw应该没问题吧

2013-08-12

13574798

发件人：jaywong notifications@github.com
发送时间：2013-08-12 16:05
主题：Re: [wasp] 入库的同时，查询报错，无法获取返回的数据 (#16)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

那应该是EG还没有上线完成。
