### ISSUE TITLE
创建索引问题

### ISSUE THREAD

**Issue by fengshiming** [alibaba/wasp#25]
```
问下wasp 创建索引的语法是什么，在wasp shell中测试一直创建不了，命令：
```

wasp(main):002:0>sql "create index PhotosByTime on Photo(user_id,time desc);"

**Comment by haosdent** [comment]
是报啥错呢，能贴下吗？

## 

haosdent
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by fengshiming** [comment]
wasp(main):001:0> sql "create index PhotosByTime on Photo(user_id,time desc);"
13/10/23 10:27:58 ERROR jdbc.JdbcStatement: exception
java.sql.SQLException: com.alibaba.wasp.jdbc.JdbcException: Operate a not supported sql: "Currently we only support the ascending and descending time field." [90170-1]
        at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:268)
        at com.alibaba.wasp.jdbc.result.ResultRemote.<init>(ResultRemote.java:96)
        at com.alibaba.wasp.jdbc.result.ResultRemote.<init>(ResultRemote.java:102)
        at com.alibaba.wasp.jdbc.command.CommandRemote.executeUpdate(CommandRemote.java:161)
        at com.alibaba.wasp.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:786)
        at com.alibaba.wasp.jdbc.JdbcStatement.execute(JdbcStatement.java:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:450)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:311)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:59)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
        at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:233)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:215)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203)
        at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
Caused by: com.alibaba.wasp.jdbc.JdbcException: Operate a not supported sql: "Currently we only support the ascending and descending time field." [90170-1]
        at com.alibaba.wasp.jdbc.JdbcException.get(JdbcException.java:176)
        ... 212 more
Caused by: com.alibaba.wasp.jdbc.JdbcSQLException: Operate a not supported sql: "Currently we only support the ascending and descending time field." [90170-1]
        at com.alibaba.wasp.jdbc.JdbcException.getJdbcSQLException(JdbcException.java:111)
        ... 213 more
Caused by: com.alibaba.wasp.plan.parser.UnsupportedException: Currently we only support the ascending and descending time field.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:95)
        at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:79)
        at com.alibaba.wasp.ipc.NettyTransceiver.processResponse(NettyTransceiver.java:518)
        at com.alibaba.wasp.ipc.NettyTransceiver.call(NettyTransceiver.java:478)
        at com.alibaba.wasp.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:160)
        at com.sun.proxy.$Proxy10.execute(Unknown Source)
        at com.alibaba.wasp.client.FClientCallable.call(FClientCallable.java:128)
        at com.alibaba.wasp.client.FClientCallable.call(FClientCallable.java:33)
        at com.alibaba.wasp.client.ServerCallable.withRetries(ServerCallable.java:153)
        at com.alibaba.wasp.client.FClient.execute(FClient.java:117)
        at com.alibaba.wasp.client.FClient.execute(FClient.java:109)
        at com.alibaba.wasp.client.FClient.execute(FClient.java:149)
        at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:256)
        ... 211 more
Caused by: org.apache.hadoop.ipc.RemoteException: Currently we only support the ascending and descending time field.
        at com.alibaba.wasp.ipc.NettyTransceiver.processResponse(NettyTransceiver.java:515)
        ... 221 more

ERROR: java.sql.SQLException: com.alibaba.wasp.jdbc.JdbcException: Operate a not supported sql: "Currently we only support the ascending and descending time field." [90170-1]

**Comment by fengshiming** [comment]
wasp(main):001:0> sql "create index PhotosByTime on Photo(user_id,time desc);"

错误信息：
13/10/23 10:27:58 ERROR jdbc.JdbcStatement: exception
java.sql.SQLException: com.alibaba.wasp.jdbc.JdbcException: Operate a not supported sql: "Currently we only support the ascending and descending time field." [90170-1]
at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:268)
at com.alibaba.wasp.jdbc.result.ResultRemote.(ResultRemote.java:96)
at com.alibaba.wasp.jdbc.result.ResultRemote.(ResultRemote.java:102)
at com.alibaba.wasp.jdbc.command.CommandRemote.executeUpdate(CommandRemote.java:161)
at com.alibaba.wasp.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:786)
at com.alibaba.wasp.jdbc.JdbcStatement.execute(JdbcStatement.java:145)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:450)
at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:311)
at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:59)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:233)
at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:215)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203)
at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
Caused by: com.alibaba.wasp.jdbc.JdbcException: Operate a not supported sql: "Currently we only support the ascending and descending time field." [90170-1]
at com.alibaba.wasp.jdbc.JdbcException.get(JdbcException.java:176)
... 212 more
Caused by: com.alibaba.wasp.jdbc.JdbcSQLException: Operate a not supported sql: "Currently we only support the ascending and descending time field." [90170-1]
at com.alibaba.wasp.jdbc.JdbcException.getJdbcSQLException(JdbcException.java:111)
... 213 more
Caused by: com.alibaba.wasp.plan.parser.UnsupportedException: Currently we only support the ascending and descending time field.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:95)
at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:79)
at com.alibaba.wasp.ipc.NettyTransceiver.processResponse(NettyTransceiver.java:518)
at com.alibaba.wasp.ipc.NettyTransceiver.call(NettyTransceiver.java:478)
at com.alibaba.wasp.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:160)
at com.sun.proxy.$Proxy10.execute(Unknown Source)
at com.alibaba.wasp.client.FClientCallable.call(FClientCallable.java:128)
at com.alibaba.wasp.client.FClientCallable.call(FClientCallable.java:33)
at com.alibaba.wasp.client.ServerCallable.withRetries(ServerCallable.java:153)
at com.alibaba.wasp.client.FClient.execute(FClient.java:117)
at com.alibaba.wasp.client.FClient.execute(FClient.java:109)
at com.alibaba.wasp.client.FClient.execute(FClient.java:149)
at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:256)
... 211 more
Caused by: org.apache.hadoop.ipc.RemoteException: Currently we only support the ascending and descending time field.
at com.alibaba.wasp.ipc.NettyTransceiver.processResponse(NettyTransceiver.java:515)
... 221 more

ERROR: java.sql.SQLException: com.alibaba.wasp.jdbc.JdbcException: Operate a not supported sql: "Currently we only support the ascending and descending time field." [90170-1]

在 2013-10-23 10:15:44，haosdent notifications@github.com 写道：
是报啥错呢，能贴下吗？

## 

haosdent
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
